version: '3.8'


services:
  palserver:
    build: .
    volumes:
       - type: bind
         source: ./data
         target: /srv/palworld/Pal/Saved/

    restart: always
    ports: 
    - "8211:8211/udp"
    - "8211:8211/tcp"
    - "25575:25575/tcp"
  paleditor:
    image: python:latest 
    volumes:
       - type: bind
         source: ./data
         target: /srv/palworld/Pal/Saved/