version: '3.8'

services:
  palserver:
    build: ./server
    volumes:
      - ./data:/srv/palworld/Pal/Saved/

    restart: always
    ports:
      - "8211:8211/udp"
      - "8211:8211/tcp"
      - "25575:25575/tcp"

  # palbackup:
  #   build: ./backup
  #   volumes:
  #     - ./data:/data
  #     - ./backups:/backups

  paleditor:
    image: python:latest
    entrypoint: bash
    volumes:
      - type: bind
        source: ./data
        target: /srv/palworld/Pal/Saved/
